In [18]:
import numpy as np

In [26]:
foo = np.array([[4,3],[1,0]])

In [27]:
foo + np.full(shape = (2,2),fill_value =5)


array([[9, 8],
       [6, 5]])

In [28]:
foo + 5

array([[9, 8],
       [6, 5]])

In [29]:
foo + [[5,5],[5,5]]

array([[9, 8],
       [6, 5]])

In [37]:
daily_wit = np.arange (5)

In [38]:
daily_wit

array([0, 1, 2, 3, 4])